# -*- coding: utf-8 -*-
"""IYANGAN_JULIUS_ARAFETALOR_DS_DAY1_ARTICLE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UfVt_vv2sxKkYas-OYDTK950FbpDmmxx
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/epidemiology.csv')

print(df.shape)

print(df.dtypes)

df.head()